name: Clojure Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@10.1
      with:
        lein: 2.9.10
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Install dependencies
      run: lein deps
      
    - name: Run tests
      run: lein test 